### ISSUE TITLE
Encontrar 5 aplicativos para analisar

### ISSUE THREAD

**Issue by G16C** [Requisitos-de-Software/2023.1-BilheteriaDigital#1]
## Descrição
Essa issue tem como objetivo a procura e seleção dos 5 aplicativos a serem avaliados, com a finalidade de escolhermos 1 como objeto de estudo na disciplina

## Tarefas
- [x] Encontrar 5 aplicativos para analise inicial

## Critério de aceitação
- [x] Os aplicativos devem ter um bom número de usuários. Também há de se levar em consideração a comunicação com estes usuários, tendo em vista facilitar o desenvolvimento do trabalho

**Comment by manuziny** [comment]
Escolhi apps de iniciativa privada e sem documentação aberta. A escolha foi tanto pelo público ser de fácil acesso para nós, quanto por serem apps conhecidos e que poderemos nos indentificar mais. Nenhum deles foi usado ainda na disciplina.

- AliExpress
- Shopee
- Shein
- Crunchyroll
- Steam

**Comment by G16C** [comment]
Para a proposta da matéria encontrei os seguintes aplicativos que poderiam ser analisados. No geral foram aplicativos que tenho bastante familiaridade por serem de uso diário, e que em algum momento já me deram um pouco de dor de cabeça.

- Duolingo
- OneFootball
- GitHub Desktop
- Discord
- Samsung Health

**Comment by mathonaut** [comment]
Escolhi os apps na sua maioria de empresas privadas. Eles possuem uma boa quantidade de usuários e de caráter bastante heterogêneo, o que facilitará nas nossas pesquisas.
- IBGE
- Moovit
- Google Podcast
- Kindle
- Reddit

**Comment by RafaelCLG0** [comment]
Selecionei esses 5 aplicativos por apresentarem um bom número de usuários que os utilizam e uma praticidade por já ter utilizados no dia a dia.

* OLX
* Mercado Livre
* MeuID
* Netshoes
* TikTok
