### ISSUE TITLE
Documentação para Entrega Final.

### ISSUE THREAD

**Issue by RafaelCLG0** [Requisitos-de-Software/2023.1-BilheteriaDigital#104]
## Descrição
Realizar a Entrega Final de acordo com os parâmetros passados pelo professor.

## Tarefas
A apresentação do projeto final da disciplina de Requisitos de Software deve possuir os seguintes tópicos:
- [x] 1) O aplicativo selecionado para o projeto.
- [x] 2) O planejamento dos recursos e das entregas (cronograma planejado e executado).
- [x] 3) A execução do projeto (as fases/etapas do desenvolvidas no projeto).
- [x] 4) Os resultados alcançados com a execução do projeto (em relação ao objetivo do projeto);
- [x] 5) Uma tabela sintetizando quais técnicas foram utilizadas na execução do projeto (em cada etapa do projeto com o(s) nome(s) do(s) participantes(s) do grupo que usou/usaram cada uma das técnicas);
- [x] 6) Uma tabela sintetizando quais artefatos foram criados no projeto em cada etapa do projeto com autor e revisor;
- [x] 7) Uma tabela sintetizando o método de verificação e validação dos artefatos com autor e revisor (do checklist e da verificação);
- [x] 8) Uma tabela sintetizando quais ferramentas e onde elas foram utilizadas em cada etapa do projeto;
- [x] 9) Uma tabela sintetizando os vídeos das apresentações de cada etapa com o(s) nome(s) do(s) participantes(s) do grupo que participaram das gravações).
- [x] A apresentação deve conter também as facilidades e dificuldades encontradas para a realização do projeto. O tempo da apresentação deve ser entre 20 até 30 minutos (tempo mínimo e máximo).

## Critério de aceitação
- [x] Seguir todas essa etapas para a Entrega Final Projeto final da disciplina

**Comment by manuziny** [comment]
Em requisitos estou com a 4 e 9

**Comment by manuziny** [comment]
itens 4 e 9 feitos

**Comment by manuziny** [comment]
Todos os tópicos estão presentes na página da entrega final.
