### ISSUE TITLE
Ajustes Pós Apresentação

### ISSUE THREAD

**Issue by G16C** [Requisitos-de-Software/2023.1-BilheteriaDigital#13]
## Descrição
Essa issue é destinada ao ajustes recomendados pelo professor e pelo monitor do grupo após a primeira apresentação.

## Tarefas
- [x] Adicionar na aba destinada às ferramentas o aplicativo para a criação de personas "This Person Does Not Exist". -Matheus
- [x] Ajustar o cronograma com mais técnicas de priorização. -Gabriel
- [x] Mudar onde estiver "verificação de sites" para "verificação de artefatos". -Geovanna
- [x] Ajustar a metodologia. -Arthur
- [x] Padronizar o histórico de versões (data e link para o perfil do git). -Arthur
- [ ] Adicionar o termo de uso. -Douglas
- [x] Trocar o padrão do botão do modo claro e escuro (usar o padrão do site gov.br). -Sidney
- [x] Atualizar o cronograma com o período de revisão baseado nos feedbacks do professor e do monitor. -Geovanna
- [x] Detalhamento do aplicativo escolhido (média complexidade e uso em ihc). -Rafael

## Critério de aceitação
- [x] Ao adicionar o novo aplicativo, o ícone deve ficar visível tanto no modo claro quanto no modo escuro.
- [x] O cronograma deve ter, no mínimo, 3 técnicas de priorização, para cumprir com o método MOSCOW.
- [x] A metodologia implementada deve ser cumprida.
- [x] É crucial que essa issue seja finalizada antes do início dos preparativos para a segunda apresentação.

**Comment by arthurmlv** [comment]
Metodologia ajustada.

**Comment by nando3d3** [comment]
Botão de modo escuro ajustado.

**Comment by manuziny** [comment]
Cronograma atualizado com período de revisão e com a troca de "páginas" para "artefatos".

**Comment by RafaelCLG0** [comment]
O detalhamento da parte do planejamento do aplicativo escolhido foi atualizado

**Comment by mathonaut** [comment]
Ferramenta This Person Does Not Exist adicionada.

**Comment by dougAlvs** [comment]
Com base nas recomendações do professor em relação ao termo de uso adicionamos uma nova aba informativa sobre isso no projeto.
