### ISSUE TITLE
Analisar projetos anteriores

### ISSUE THREAD

**Issue by arthurgrandao** [Requisitos-de-Software/2023.1-BilheteriaDigital#2]
## Descrição
Procurar e analisar projetos anteriores para auxiliar nosso projeto.

## Tarefas

- [x] Procurar e analisar os projetos anteriores;
- [x] Listar as técnicas, tecnologias e metodologias utilizadas;

## Critério de aceitação

- [x] Apresentar ao grupo o resultado da pesquisa;

**Comment by mathonaut** [comment]
A análise se deu nos repositórios de cada projeto presente na organização da disciplina. Foram analisados ao todo 57 projetos levando em conta as suas tecnologias, metodologias e técnicas utilizadas.

Inicialmente é possível destacar as tecnologias utilizadas, foi observado que elas eram as mesmas presentes nos projetos de IHC, com pequenas mudanças para adequar ao que é exigido na disciplina. 

Em relação a metodologias e técnicas, elas não possuem uma estrutura consistente sendo uma mistura de vários aspectos das metodologias ágeis, como o desenvolvimento por pares, a entrega contínua e a divisão de trabalho por sprints.

Abaixo segue a lista com os apps já utilizados:

- Antenna Pod
- Audible
- BikeItau
- BRB mobilidade
- Caixa Tem
- Carteira de Trabalho Digital
- Carteira Digital Transito
- Conecte SUS
- Coronavírus-SUS
- Correios
- Deezer
- Detran DF
- Disney Plus
- Doarti
- Duolingo
- ENEM
- e-Título
- ExercitoBrasileiro
- FifaPlus
- GoogleMaps
- Grasshopper
- Guardioes da Saúde
- Hemovida
- iFut
- Ingresso.com
- Jitsi-Meet
- Lichess
- LinkedIn
- MedSUS
- MEI
- Metrô DF
- Meu-Gov.br
- Mia-Ajuda
- Moodle
- Noruh
- Notion
- PlantJammer
- Ponto Fácil
- PrimeVideo
- Promobit
- Rappi
- Rico
- Shazam
- Sinesp
- StarPlus
- Steam
- Telegram
- Tembici
- Tesouro Direto
- TikTok
- Twitter
- VivaBem
- Waze
- Wikipedia
- Wire
- Yellow
- Youtube
