### ISSUE TITLE
Introspecção

### ISSUE THREAD

**Issue by manuziny** [Requisitos-de-Software/2023.1-BilheteriaDigital#24]
## Descrição
Realizar a técnica da introspecção para elicitação de requisitos.

## Tarefas

- [x] Reunir-se para executar a técnica

## Critério de aceitação

- [x] Documentar os resultados
- [x] Adicionar na aba "Elicitação" > "Ténicas" no site.

**Comment by arthurmlv** [comment]
Introspecção realizada.
