### ISSUE TITLE
Priorização dos requisitos levantados

### ISSUE THREAD

**Issue by manuziny** [Requisitos-de-Software/2023.1-BilheteriaDigital#27]
## Descrição
Utilizar as ténicas de priorização de acordo com as técnicas selecionadas que são: 100 Dólares (Arthur), Three Level Scale (Douglas) e First Things First (Matheus, Rafael, Sidney).

## Tarefas

- [x] Convidar usuários para participarem da técnica.
- [x] Reunir para documentar resultados.

## Critério de aceitação

- [x] Ter tudo documentado.
- [x] Estar no site em "Elicitação" > "Técnicas

**Comment by nando3d3** [comment]
First Things First pronto
