### ISSUE TITLE
Análise dos apps

### ISSUE THREAD

**Issue by manuziny** [Requisitos-de-Software/2023.1-BilheteriaDigital#3]
## Descrição
Analisar os aplicativos que cada membro escolheu para que possamos iniciar as pesquisas do projeto.

## Tarefas

- [x] Escolher e justificar a escolha do aplicativo
- [x] Verificar se há documentação aberta

## Critério de aceitação

- [x] Os aplicativos não podem ter documentação aberta
- [x] A justificativa precisa ser baseada nos conceitos da disciplina

**Comment by dougAlvs** [comment]
Após debater as opções apresentadas pelos colegas de equipe chegamos a conclusão que o aplicativo Shopee é uma boa escolha para o projeto da disciplina. Alguns pontos positivos são:
* Perfil de usuário bem abrangente e de fácil acesso em caso de entrevistas e pesquisas.
* O aplicativo não foi escolhido em outros semestres da disciplina e não há documentação aberta sobre os requisitos.

**Comment by manuziny** [comment]
Devido a opiniões tanto do professor quanto de alguns colegas, decidimos trocar de aplicativo para que houvesse uma integração com o trabalho de IHC, portanto adotamos o Bilheteria Digital como app.
