### ISSUE TITLE
Verificação especificação suplementar: grupo 2

### ISSUE THREAD

**Issue by manuziny** [Requisitos-de-Software/2023.1-BilheteriaDigital#73]
## Descrição
Documentação da verificação do artefato especificação suplementar do grupo 2.

## Tarefas

- [x] Criação da checklist
- [x] Possuir introdução, metodologia, desenvolvimento e sugestões 
- [x] Gráficos (opcional)
- [x] Especificar qual a versão que está sendo verificada.

## Critério de aceitação

- [x] Estar na gitpage
- [x] Possuir o padrão requisitado

**Comment by mathonaut** [comment]
Concluída.
